package:
    name:           omnipay-qiwi
    namespace:      hiqdev\php\merchant\qiwi
    title:          Qiwi driver for Omnipay PHP payment library
    type:           library
    license:        MIT
    keywords:       php, omnipay, qiwi, merchant, payment
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [Qiwi](https://qiwi.ru/) support for Omnipay.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
